* Fixed diverse occurences of $sess_id in nxnode, when hostname   contains whitespace.   (fabianx@bat.berlios.de)

diff --git a/freenx-server/trunk/nxnode b/freenx-server/trunk/nxnode
--- a/freenx-server/trunk/nxnode
+++ b/freenx-server/trunk/nxnode
@@ -494,7 +494,7 @@ node_start_agent()
 		
 		# Start the agent
 		
-		$PATH_BIN/nxviewer -encodings tight hextile copyrect raw -passwd $USER_FAKE_HOME/.nx/C-$sess_id/scripts/.passwd -name "NX - $user@$SERVER_NAME:$display - $session (GPL Edition)" -option "$USER_FAKE_HOME/.nx/C-$sess_id/options" $vncfullscreen $G $K $agent_server $AGENT_EXTRA_OPTIONS_RFB 2>&3 &
+		$PATH_BIN/nxviewer -encodings tight hextile copyrect raw -passwd "$USER_FAKE_HOME/.nx/C-$sess_id/scripts/.passwd" -name "NX - $user@$SERVER_NAME:$display - $session (GPL Edition)" -option "$USER_FAKE_HOME/.nx/C-$sess_id/options" $vncfullscreen $G $K $agent_server $AGENT_EXTRA_OPTIONS_RFB 2>&3 &
 
 	elif [ "$R" = "-R" -a "$rootless" != "1" ]
 	then
@@ -1118,7 +1118,7 @@ startsession()
 	umask 0022
 	mkdir -p $USER_FAKE_HOME
 	umask 0077
-	mkdir -p $USER_FAKE_HOME/.nx/C-$sess_id
+	mkdir -p "$USER_FAKE_HOME/.nx/C-$sess_id"
 	umask $OLD_UMASK
 	
 	# cache=8M,images=32M,pack=nopack,link=lan,type=unix-kde,cleanup=0,accept=192.168.1.66,cookie=E38A94A77F975443AF04EC911881B120,id=Knoppix-1000-6A8269CC467264EAEF6349D062689755,samba=1,render=1:1000
@@ -1155,7 +1155,7 @@ startsession()
 	OLD_UMASK=$(umask)
 	umask 0077
 
-cat << EOF > $USER_FAKE_HOME/.nx/C-$sess_id/options
+cat << EOF > "$USER_FAKE_HOME/.nx/C-$sess_id/options"
 ${kbtype:+kbtype=$kbtype,}${kbload:+kbload=$kbload,}${keymap:+keymap=$keymap,}${resize:+resize=$resize,}${CACHE}${IMAGES}${PACK}link=$link,nodelay=$nodelay,type=$realtype,cleanup=0,${ACCEPT}cookie=$proxy_cookie,id=$sess_id,samba=$samba,media=$media${sync:+,sync=$sync}${cups:+,cups=$cups}${keybd:+,keybd=$keybd}${http:+,http=$http}${rdpcolors:+,rdpcolors=$rdpcolors}${rdpcache:+,rdpcache=$rdpcache}${fullscreen:+,fullscreen=1}:$display
 EOF
 	umask $OLD_UMASK
@@ -1177,9 +1177,9 @@ add unix:$display MIT-MAGIC-COOKIE-1 $cookie
 exit
 EOF
 
-	mkdir -m700 $USER_FAKE_HOME/.nx/C-$sess_id/scripts/ 2>/dev/null || chmod 700 $USER_FAKE_HOME/.nx/C-$sess_id/scripts/
+	mkdir -m700 "$USER_FAKE_HOME/.nx/C-$sess_id/scripts/" 2>/dev/null || chmod 700 "$USER_FAKE_HOME/.nx/C-$sess_id/scripts/"
 
-cat << EOF >$USER_FAKE_HOME/.nx/C-$sess_id/scripts/authority
+cat << EOF >"$USER_FAKE_HOME/.nx/C-$sess_id/scripts/authority"
 remove localhost:$display
 remove unix:$display
 exit
@@ -1187,16 +1187,16 @@ EOF
 
 if [ "$1" = "restore" ]
 then
-	echo > $USER_FAKE_HOME/.nx/C-$sess_id/session
-	sh -c 'echo "Info: tail -f running with pid '\'\$$\''."; exec tail -n1 -f '$USER_FAKE_HOME'/.nx/C-'$sess_id'/session' | node_start_monitor "$1" "$status" &
+	echo > "$USER_FAKE_HOME/.nx/C-$sess_id/session"
+	sh -c 'echo "Info: tail -f running with pid '\'\$$\''."; exec tail -n1 -f '"$USER_FAKE_HOME"'/.nx/C-'"$sess_id"'/session' | node_start_monitor "$1" "$status" &
 
 	MONITOR_PID=$!
 	export MONITOR_PID
 
-	mkdir -p $USER_FAKE_HOME/.nx/C-$sess_id/pids/
-	echo "$MONITOR_PID" > $USER_FAKE_HOME/.nx/C-$sess_id/pids/monitor
+	mkdir -p "$USER_FAKE_HOME/.nx/C-$sess_id/pids/"
+	echo "$MONITOR_PID" > "$USER_FAKE_HOME/.nx/C-$sess_id/pids/monitor"
 
-	node_suspend_session $sess_id || { echo "Info: Reconnection failed: NX Agent process could not be found." >>"$USER_FAKE_HOME/.nx/C-$sess_id/session"; node_fail_restore_session $sess_id; }
+	node_suspend_session "$sess_id" || { echo "Info: Reconnection failed: NX Agent process could not be found." >>"$USER_FAKE_HOME/.nx/C-$sess_id/session"; node_fail_restore_session "$sess_id"; }
 else
 	node_start_agent &
 	node_start_applications &
@@ -1204,7 +1204,6 @@ fi
 
 if which "$NODE_AUTOSTART" >/dev/null 2>&1
 then
-	sess_id="$SERVER_NAME-$display-$uniqueid"
 	# go into background immediately
 	NXSESSIONID="$sess_id" DISPLAY=unix:$display "$NODE_AUTOSTART" "$1" >/dev/null 2>&1 &
 	# dont't wait for this child!
@@ -1338,7 +1337,7 @@ cmd_node_addprinter()
 		mkdir -p "$USER_FAKE_HOME/.nx/config/ppd/"
 		if [ "$MODEL" = "download_new" -o ! -r "$USER_FAKE_HOME/.nx/config/ppd/$printer.ppd" ]
 		then
-			curl --digest -o "$USER_FAKE_HOME/.nx/config/ppd/$printer.ppd" "http://$username:$password@127.0.0.1:$port/ppd/${printer}_nxdl.ppd" >>$USER_FAKE_HOME/.nx/C-$sess_id/cups/curl.log 2>&1
+			curl --digest -o "$USER_FAKE_HOME/.nx/config/ppd/$printer.ppd" "http://$username:$password@127.0.0.1:$port/ppd/${printer}_nxdl.ppd" >>"$USER_FAKE_HOME/.nx/C-$sess_id/cups/curl.log" 2>&1
 		RC=$?
 		[ $RC -eq 0 -a "$ENABLE_CUPS_SEAMLESS" != "1" ] && $PATH_BIN/nxclient --message "Download successful." -display :$display
 		[ $RC -ne 0 -a "$ENABLE_CUPS_SEAMLESS" != "1" ] && $PATH_BIN/nxclient --message "Download failed. Log is: $USER_FAKE_HOME/.nx/C-$sess_id/cups/curl.log" -display :$display
