Changed interactive mode to be less lines. Added:
	- Enforcing of configuration check
	- Test of the connection to the server
		- Warning if version mismatches

diff --git a/freenx-server/branches/FreeNX-0.4/nxsetup b/freenx-server/branches/FreeNX-0.4/nxsetup
--- a/freenx-server/branches/FreeNX-0.4/nxsetup
+++ b/freenx-server/branches/FreeNX-0.4/nxsetup
@@ -52,23 +52,20 @@ done
 [ "$UNINSTALL" = "yes" -a "$CLEAN" = "yes" ] && HELP="yes"
 [ "$SETUP_SSH2_KEY" = "yes" -a "$SETUP_NOMACHINE_KEY" = "no" ] && HELP="yes"
 
-if [ "$INSTALL" = "no" -a "$UNINSTALL" = "no" ]
+if [ "$INSTALL" = "no" -a "$UNINSTALL" = "no" -a "$AUTOMATIC" = "no" ]
 then
-	if [ "$AUTOMATIC" = "no" -a "$HELP" = "no" ]
-	then
-		echo "------> You did select no action."
-		echo "        FreeNX guesses that you want to _install_ the"
-		echo "        server."
-		echo "        Use --help to get help contents."
-		echo ""
-		echo -n "Do you want to abort now? [y/N] "
-		read -n 1 CHOICE
-		echo
-		[ "$CHOICE" = "y" ] && HELP="yes"
-	else
-		HELP="yes"
-	fi
+	echo "------> You did select no action."
+	echo "        FreeNX guesses that you want to _install_ the"
+	echo "        server."
+	echo "        Use --help to get help contents."
+	echo ""
+	echo -n "Do you want to abort now? [y/N] "
+	read -n 1 CHOICE
+	echo
+	[ "$CHOICE" = "y" ] || INSTALL="yes"
 fi
+
+[ "$INSTALL" = "no" -a "$UNINSTALL" = "no" ] && HELP="yes"
 
 if [ "$HELP" = "yes" ]
 then
@@ -237,6 +234,21 @@ install_nx()
 no-port-forwarding,no-X11-forwarding,no-agent-forwarding,command="$PATH_BIN/nxserver" ssh-dss AAAAB3NzaC1kc3MAAACBAJe/0DNBePG9dYLWq7cJ0SqyRf1iiZN/IbzrmBvgPTZnBa5FT/0Lcj39sRYt1paAlhchwUmwwIiSZaON5JnJOZ6jKkjWIuJ9MdTGfdvtY1aLwDMpxUVoGwEaKWOyin02IPWYSkDQb6cceuG9NfPulS9iuytdx0zIzqvGqfvudtufAAAAFQCwosRXR2QA8OSgFWSO6+kGrRJKiwAAAIEAjgvVNAYWSrnFD+cghyJbyx60AAjKtxZ0r/Pn9k94Qt2rvQoMnGgt/zU0v/y4hzg+g3JNEmO1PdHh/wDPVOxlZ6Hb5F4IQnENaAZ9uTZiFGqhBO1c8Wwjiq/MFZy3jZaidarLJvVs8EeT4mZcWxwm7nIVD4lRU2wQ2lj4aTPcepMAAACANlgcCuA4wrC+3Cic9CFkqiwO/Rn1vk8dvGuEQqFJ6f6LVfPfRTfaQU7TGVLk2CzY4dasrwxJ1f6FsT8DHTNGnxELPKRuLstGrFY/PR7KeafeFZDf+fJ3mbX5nxrld3wi5titTnX+8s4IKv29HJguPvOK/SI7cjzA+SqNfD7qEo8= root@nettuno
 EOF
 			chmod 600 $NX_HOME_DIR/.ssh/$SSH_AUTHORIZED_KEYS
+			cat << EOF >$NX_HOME_DIR/.ssh/client.id_dsa.key
+-----BEGIN DSA PRIVATE KEY-----
+MIIBuwIBAAKBgQCXv9AzQXjxvXWC1qu3CdEqskX9YomTfyG865gb4D02ZwWuRU/9
+C3I9/bEWLdaWgJYXIcFJsMCIkmWjjeSZyTmeoypI1iLifTHUxn3b7WNWi8AzKcVF
+aBsBGiljsop9NiD1mEpA0G+nHHrhvTXz7pUvYrsrXcdMyM6rxqn77nbbnwIVALCi
+xFdHZADw5KAVZI7r6QatEkqLAoGBAI4L1TQGFkq5xQ/nIIciW8setAAIyrcWdK/z
+5/ZPeELdq70KDJxoLf81NL/8uIc4PoNyTRJjtT3R4f8Az1TsZWeh2+ReCEJxDWgG
+fbk2YhRqoQTtXPFsI4qvzBWct42WonWqyyb1bPBHk+JmXFscJu5yFQ+JUVNsENpY
++Gkz3HqTAoGANlgcCuA4wrC+3Cic9CFkqiwO/Rn1vk8dvGuEQqFJ6f6LVfPfRTfa
+QU7TGVLk2CzY4dasrwxJ1f6FsT8DHTNGnxELPKRuLstGrFY/PR7KeafeFZDf+fJ3
+mbX5nxrld3wi5titTnX+8s4IKv29HJguPvOK/SI7cjzA+SqNfD7qEo8CFDIm1xRf
+8xAPsSKs6yZ6j1FNklfu
+-----END DSA PRIVATE KEY-----
+EOF
+			chmod 600 $NX_HOME_DIR/.ssh/client.id_dsa.key
 		else
 			# generate a new key, backup the old and copy it to $SSH_AUTHORIZED_KEYS
 			$PATH_BIN/nxkeygen
@@ -291,7 +303,43 @@ EOF
 
 test_nx()
 {
-	:	
+	echo ""
+	echo "----> Testing your nxserver configuration ..."
+	. $(PATH=$(cd $(dirname $0) && pwd):$PATH which nxloadconfig) --check
+	echo "<---- done"
+	
+	echo "----> Testing your nxserver connection ..."
+	
+	CONNECTION=""
+	while read -t 3 line
+	do
+		case "$line" in
+			*"HELLO NXSERVER - Version $NX_VERSION"*)
+				CONNECTION="yes"
+			;;
+			*"HELLO NXSERVER - Version"*)
+				echo "Warning: Version Mismatch. Expected $NX_VERSION got: $line."
+				CONNECTION="yes"
+			;;
+			*"NX> 999 Bye"*)
+				break;
+			;;
+		esac
+		echo $line
+	done < <(echo "quit" | ssh -i $NX_HOME_DIR/.ssh/client.id_dsa.key -p "$SSHD_PORT" nx@127.0.0.1 -o "RhostsAuthentication no" -o "PasswordAuthentication no" -o "RSAAuthentication no" -o "RhostsRSAAuthentication no" -o "PubkeyAuthentication yes" -o "PreferredAuthentications publickey" nxserver)
+	if [ -z "$CONNECTION" ]
+	then
+		echo "Fatal error: Could not connect to NX Server."
+		echo 
+		echo "Please check your ssh setup:"
+		echo ""
+		echo "	- Make sure nx is one of the AllowUsers in sshd_config."
+		echo "	- Make sure your sshd allows public key authentication."
+		echo "	- Make sure your sshd is really running on port $SSHD_PORT."
+		echo "	- Make sure your sshd_config AuthorizedKeysFile in sshd_config is set to $SSH_AUTHORIZED_KEYS."
+		exit 1
+	fi
+	echo "<--- done"
 }
 
 uninstall_nx() 
